[package]
name        = "flair-rs"
version     = "0.2.1"
edition     = "2024"
authors = ["Andyou <andyou@animagram.jp>"]
description = "Wasm-compilable implement of time series forecasting algorithm FLAIR."
license     = "Apache-2.0"
repository  = "https://github.com/animagram-jp/flair"
keywords    = ["forecasting", "time-series", "wasm", "no-std", "statistics"]
categories  = ["science", "no-std", "wasm"]
readme      = ["examples/dataset/"]

[features]
default = []
std = []

[dependencies]
libm = "0.2"

[dev-dependencies]
nalgebra = "0.35"

[lib]
name = "flair"
path = "src/lib.rs"

[package.metadata.docs.rs]
all-features = true
